services:
  device-registry-db:
    image: postgres:16-alpine
    container_name: pulsegrid-device-registry-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: device_registry_db
      POSTGRES_USER: device_registry_user
      POSTGRES_PASSWORD: device_registry_pass
    ports:
      - "5440:5432"
    volumes:
      - device_registry_db_data:/var/lib/postgresql/data

  device-registry:
    build:
      context: ./backend/device-registry
    container_name: pulsegrid-device-registry
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://device-registry-db:5432/device_registry_db
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - device-registry-db
      - kafka

  aggregation-service-db:
    image: timescale/timescaledb:latest-pg16
    container_name: pulsegrid-aggregation-service-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: aggregation_service_db
      POSTGRES_USER: aggregation_service_user
      POSTGRES_PASSWORD: aggregation_service_pass
    ports:
      - "5441:5432"
    volumes:
      - aggregation_service_db_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:4.3.1
    container_name: pulsegrid-kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:7-alpine
    container_name: pulsegrid-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  ingestion-gateway:
    build:
      context: ./backend/ingestion-gateway
    container_name: pulsegrid-ingestion-gateway
    restart: unless-stopped
    ports:
      - "8091:8091"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DEVICE_REGISTRY_BASE_URL: http://device-registry:8090
    depends_on:
      - device-registry
      - kafka
      - redis

volumes:
  device_registry_db_data:
  aggregation_service_db_data:
