apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alerting-service-db
spec:
  serviceName: alerting-service-db
  replicas: 1
  selector:
    matchLabels:
      app: alerting-service-db
  template:
    metadata:
      labels:
        app: alerting-service-db
    spec:
      containers:
        - name: alerting-service-db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: alerting-service-db-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: alerting-service-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alerting-service-db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
