apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-workers-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://notification-workers-db:5432/notification_workers_db
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  MAIL_HOST: mailpit
  MAIL_PORT: "1025"
  NOTIFICATIONS_EMAIL_FROM: alerts@pulsegrid.local
  NOTIFICATIONS_EMAIL_TO: ops-team@pulsegrid.local
