apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-workers
  labels:
    app: notification-workers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-workers
  template:
    metadata:
      labels:
        app: notification-workers
    spec:
      terminationGracePeriodSeconds: 45
      containers:
        - name: notification-workers
          image: docker.io/perblue/notification-workers:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8094
          envFrom:
            - configMapRef:
                name: notification-workers-config
            - secretRef:
                name: notification-workers-secret
          resources:
            requests:
              cpu: 250m
              memory: 384Mi
            limits:
              cpu: "1"
              memory: 768Mi
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 10
            failureThreshold: 3
