apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notification-workers-db
spec:
  serviceName: notification-workers-db
  replicas: 1
  selector:
    matchLabels:
      app: notification-workers-db
  template:
    metadata:
      labels:
        app: notification-workers-db
    spec:
      containers:
        - name: notification-workers-db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: notification-workers-db-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: notification-workers-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-workers-db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
