apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregation-service-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://aggregation-service-db:5432/aggregation_service_db
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
