apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregation-service
  labels:
    app: aggregation-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aggregation-service
  template:
    metadata:
      labels:
        app: aggregation-service
    spec:
      containers:
        - name: aggregation-service
          image: docker.io/perblue/aggregation-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8092
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: aggregation-service-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: aggregation-service-config
                  key: SPRING_KAFKA_BOOTSTRAP_SERVERS
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: aggregation-service-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aggregation-service-secret
                  key: SPRING_DATASOURCE_PASSWORD
