apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestion-gateway-config
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  DEVICE_REGISTRY_BASE_URL: http://device-registry:8090
